Hw5 react storybook
Eugen-der-edle-Ritter/Griffit-automaton pull request #4
Opened 2021-10-06 08:49 UTC by Eugen-der-edle-Ritter

Перенес UI интерфейс в React компоненты, создал библиотеку компонентов Storybook, подключил Chromatic, обновил файл readme (внес описание проекта + инструкции по работе с приложением)

2021-10-15 06:48 UTC, nickovchinnikov commented
В каждом PR у тебя код всего приложения. Не надо так.
ПРочитай фидбек и сделай доработки по предыдущему PR. Там много важного
В рамках этого PR я не вижу

1) Тестов по компонентам.
2) Ты оставил работу с канвасом, хотя цель это разобраться с декларативностью и использовать элементы

Что с покрытием?

2021-10-15 06:50 UTC, nickovchinnikov requested changes
Нужно закончить работу с предыдущими правками, там много важного
Давай переходить от canvas к HTML элементам, это позволит тебе поработать декларативно с компонентами (важно)
Нужно писать тесты для компонентов
https://testing-library.com/docs/react-testing-library/intro

2021-10-15 06:50 UTC, nickovchinnikov commented on .eslintrc.js
> +module.exports = {
Этот файл был в предыдущем PR, приходится проверять всю работу каждый раз (

2021-10-15 06:50 UTC, nickovchinnikov commented on public/style.css
> +/* @import url('https://fonts.googleapis.com/css2?family=Roboto&display=swap'); */
закоментированные блоки кода

2021-10-15 06:50 UTC, nickovchinnikov commented on src/components/App.tsx
> +// import { useInterval } from '@/hooks/useInterval';
закоментированный код в PR

2021-10-15 06:50 UTC, nickovchinnikov commented on src/components/App.tsx
> +export const App: FC = () => {
Где тесты для компонента?

2021-10-15 06:50 UTC, nickovchinnikov commented on src/components/ControlPanel/ControlPanel.tsx
> +import React, { FC, ChangeEvent } from 'react';
Где тесты для компонента?

2021-10-15 06:50 UTC, nickovchinnikov commented on src/components/Display/Display.tsx
> +  const canvasRef = useRef<HTMLCanvasElement>(null);
А давай сделаем вместо канваса работу с HTML элементами
У тебя есть компонент ячейка и далее ты пилишь декларативно рендеринг и работу с компонентами

2021-10-15 06:50 UTC, nickovchinnikov commented on src/components/hooks/useInterval.ts
> +import { useEffect, useRef } from 'react';
Два одинаковых хука? А где тесты?

2021-10-20 10:08 UTC, Eugen-der-edle-Ritter commented on public/style.css
> +/* @import url('https://fonts.googleapis.com/css2?family=Roboto&display=swap'); */
убрал

2021-10-23 09:37 UTC, merged